In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings("ignore")

In [ ]:
#Load dataset
df = pd.read_csv('/content/song_recomendation_B.csv')

#Head of dataset
df.head()

,Track URI,Track Name,Artist Name(s),Album Name,Album Release Date,Popularity,Artist Genres,Danceability,Energy,Key,Loudness,Mode,Speechiness,Acousticness,Instrumentalness,Liveness,Valence,Tempo,Time Signature
0,spotify:track:6a8GbQIlV8HBUW3c6Uk9PH,I Know You Want Me (Calle Ocho),Pitbull,Pitbull Starring In Rebelution,2009-10-23,64,"dance pop,miami hip hop,pop",0.825,0.743,2.0,-5.995,1.0,0.1490,0.0142,0.000021,0.2370,0.800,127.045,4.0
1,spotify:track:70XtWbcVZcpaOddJftMcVi,From the Bottom of My Broken Heart,Britney Spears,...Baby One More Time (Digital Deluxe Version),1999-01-12,56,"dance pop,pop",0.677,0.665,7.0,-5.171,1.0,0.0305,0.5600,NaN,0.3380,0.706,74.981,4.0
2,spotify:track:72WZtWs6V7uu3aMgMmEkYe,You Can't Always Get What You Want,The Rolling Stones,Let It Bleed,1969-12-05,0,"album rock,british invasion,classic rock,rock",0.319,0.627,0.0,-9.611,1.0,0.0687,0.6750,0.000073,0.2890,0.497,85.818,4.0
3,spotify:track:4bEb3KE4mSKlTFjtWJQBqO,Don't Stop - 2004 Remaster,Fleetwood Mac,Rumours,1977-02-04,79,"album rock,classic rock,rock,soft rock,yacht rock",0.671,0.710,9.0,-7.724,1.0,0.0356,0.0393,0.000011,0.0387,0.834,118.745,4.0
4,spotify:track:0d2iYfpKoM0QCKvcLCkBao,Eastside (with Halsey & Khalid),"benny blanco, Halsey, Khalid",Eastside (with Halsey & Khalid),2018-07-12,78,"pop,electropop,etherpop,indie poptimism,pop,po...",0.560,0.680,6.0,-7.648,0.0,0.3210,0.5550,0.000000,0.1160,0.319,89.391,4.0

In [ ]:
df.shape

(4999, 19)

Data terdiri dari 4999 baris dan 19 kolom.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4999 entries, 0 to 4998
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Track URI           4999 non-null   object
 1   Track Name          4999 non-null   object
 2   Artist Name(s)      4999 non-null   object
 3   Album Name          4999 non-null   object
 4   Album Release Date  4997 non-null   object
 5   Popularity          4999 non-null   int64
 6   Artist Genres       4744 non-null   object
 7   Danceability        4747 non-null   float64
 8   Energy              4997 non-null   float64
 9   Key                 4997 non-null   float64
 10  Loudness            4997 non-null   float64
 11  Mode                4997 non-null   float64
 12  Speechiness         4997 non-null   float64
 13  Acousticness        4997 non-null   float64
 14  Instrumentalness    4897 non-null   float64
 15  Liveness            4997 non-null   float64
 16  Valence             4997 non-null   float64
 17  Tempo               4997 non-null   float64
 18  Time Signature      4997 non-null   float64
dtypes: float64(12), int64(1), object(6)
memory usage: 742.2+ KB

# a. Conduct an Exploratory Data Analysis (EDA) on the dataset. Highlight the main insights and any irregularities you find, and address those anomalies appropriately!

## Check Data Problems

In [ ]:
#Check duplicate
df.duplicated().sum()

np.int64(13)

Terdapat 13 baris duplikat.

In [ ]:
#Handle duplicates
df = df.drop_duplicates()

Semua baris yang duplikat di drop agar analisis tidak bias dan tidak memengaruhi clustering.

In [ ]:
#Check Inconsistent
for col in df.columns:
    print(f"\nColumn: {col}")
    print(df[col].dropna().unique())

Column: Track URI
['spotify:track:6a8GbQIlV8HBUW3c6Uk9PH'
 'spotify:track:70XtWbcVZcpaOddJftMcVi'
 'spotify:track:72WZtWs6V7uu3aMgMmEkYe' ...
 'spotify:track:6PUzxtIHkv346yP89NzP9X'
 'spotify:track:3kcKlOkQQEPVwxwljbGJ5p'
 'spotify:track:5ydeCNaWDmFbu4zl0roPAH']

Column: Track Name
['I Know You Want Me (Calle Ocho)' 'From the Bottom of My Broken Heart'
 "You Can't Always Get What You Want" ... 'Kernkraft 400'
 'Kernkraft 400 (A Better Day)'
 "Groovejet (If This Ain't Love) [feat. Sophie Ellis-Bextor]"]

Column: Artist Name(s)
['Pitbull' 'Britney Spears' 'The Rolling Stones' ... 'Creeds'
 'Zombie Nation' 'Spiller, Sophie Ellis-Bextor']

Column: Album Name
['Pitbull Starring In Rebelution'
 '...Baby One More Time (Digital Deluxe Version)' 'Let It Bleed' ...
 'Kernkraft 400 Single Mixes' 'Kernkraft 400 (A Better Day)'
 "Groovejet (If This Ain't Love) [feat. Sophie Ellis-Bextor]"]

Column: Album Release Date
['2009-10-23' '1999-01-12' '1969-12-05' ... '2023-03-31' '2006-03-07'
 '2022-06-17']

Column: Popularity
[64 56  0 79 78 61 80  5 15 68 73 47 74 82 30 87 22 66 13 27 83 84 52 65
 72 63  7 85 58 49 37 43 57 35 62 12 77 71 33 54 69 59 36 24  3 60 40 67
 42 81 20 31 18 53  6 70 44 96 48 51 45 55 76 46  8 21 25 23 39 50  4 38
 28 17 10 34 11 19 91  2 75 26  9 93 41 14 86  1 29 16 89 32 90 98 95 88
 94 92 97]

Column: Artist Genres
['dance pop,miami hip hop,pop' 'dance pop,pop'
 'album rock,british invasion,classic rock,rock' ... 'big beat,breakbeat'
 'german techno' 'disco house,vocal house,dance pop,europop,new wave pop']

Column: Danceability
[0.825 0.677 0.319 0.671 0.56  0.48  0.562 0.557 0.652 0.813 0.736 0.261
 0.667 0.862 0.393 0.64  0.692 0.672 0.68  0.534 0.681 0.485 0.924 0.735
 0.719 0.748 0.836 0.951 0.737 0.632 0.561 0.742 0.604 0.617 0.787 0.515
 0.45  0.769 0.653 0.421 0.783 0.571 0.648 0.937 0.839 0.852 0.702 0.52
 0.542 0.706 0.553 0.689 0.379 0.529 0.398 0.591 0.662 0.254 0.867 0.709
 0.661 0.612 0.551 0.334 0.663 0.69  0.654 0.66  0.32  0.384 0.799 0.497
 0.704 0.35  0.605 0.6   0.61  0.429 0.43  0.649 0.423 0.374 0.607 0.723
 0.366 0.716 0.627 0.707 0.613 0.524 0.552 0.697 0.674 0.594 0.533 0.638
 0.516 0.545 0.895 0.514 0.446 0.415 0.765 0.767 0.797 0.223 0.645 0.482
 0.635 0.535 0.633 0.581 0.647 0.646 0.234 0.668 0.585 0.698 0.854 0.768
 0.59  0.683 0.781 0.641 0.741 0.837 0.471 0.725 0.757 0.518 0.589 0.693
 0.76  0.597 0.611 0.731 0.385 0.724 0.905 0.883 0.595 0.563 0.528 0.929
 0.678 0.762 0.582 0.675 0.676 0.665 0.347 0.418 0.235 0.438 0.74  0.538
 0.687 0.579 0.743 0.466 0.616 0.408 0.711 0.715 0.67  0.396 0.618 0.957
 0.602 0.872 0.749 0.476 0.63  0.573 0.712 0.587 0.498 0.426 0.493 0.388
 0.739 0.576 0.726 0.309 0.796 0.708 0.745 0.55  0.521 0.703 0.481 0.49
 0.383 0.659 0.483 0.51  0.5   0.566 0.619 0.592 0.785 0.71  0.686 0.574
 0.468 0.889 0.406 0.858 0.351 0.409 0.696 0.431 0.908 0.842 0.556 0.511
 0.478 0.568 0.682 0.394 0.549 0.624 0.583 0.666 0.491 0.405 0.761 0.389
 0.756 0.601 0.439 0.531 0.268 0.713 0.83  0.628 0.324 0.754 0.764 0.717
 0.522 0.336 0.452 0.791 0.701 0.827 0.372 0.564 0.537 0.718 0.445 0.402
 0.243 0.782 0.766 0.596 0.417 0.685 0.572 0.368 0.794 0.593 0.558 0.419
 0.543 0.276 0.934 0.944 0.241 0.192 0.196 0.775 0.634 0.844 0.755 0.555
 0.163 0.699 0.658 0.299 0.888 0.371 0.727 0.27  0.622 0.777 0.283 0.548
 0.656 0.463 0.266 0.615 0.489 0.926 0.433 0.828 0.404 0.684 0.46  0.554
 0.412 0.499 0.623 0.586 0.657 0.817 0.751 0.7   0.608 0.838 0.505 0.486
 0.444 0.806 0.62  0.878 0.721 0.523 0.746 0.65  0.536 0.322 0.434 0.263
 0.625 0.312 0.509 0.392 0.546 0.544 0.938 0.356 0.644 0.948 0.458 0.453
 0.877 0.788 0.803 0.462 0.81  0.359 0.636 0.732 0.382 0.78  0.773 0.841
 0.314 0.885 0.317 0.73  0.729 0.598 0.824 0.295 0.461 0.451 0.447 0.58
 0.637 0.33  0.798 0.747 0.39  0.856 0.669 0.93  0.492 0.609 0.37  0.832
 0.705 0.85  0.377 0.861 0.819 0.606 0.473 0.778 0.484 0.629 0.892 0.436
 0.532 0.259 0.53  0.487 0.565 0.508 0.373 0.758 0.728 0.812 0.82  0.501
 0.364 0.218 0.488 0.303 0.365 0.57  0.232 0.643 0.448 0.734 0.541 0.688
 0.504 0.454 0.722 0.818 0.859 0.284 0.525 0.72  0.479 0.228 0.547 0.584
 0.316 0.673 0.651 0.642 0.843 0.939 0.503 0.494 0.399 0.679 0.631 0.54
 0.763 0.733 0.411 0.47  0.577 0.694 0.539 0.784 0.425 0.848 0.459 0.469
 0.294 0.904 0.578 0.771 0.477 0.333 0.28  0.975 0.639 0.575 0.884 0.801
 0.441 0.816 0.129 0.569 0.831 0.695 0.435 0.655 0.923 0.869 0.443 0.759
 0.506 0.251 0.772 0.343 0.847 0.916 0.344 0.437 0.744 0.802 0.804 0.821
 0.495 0.4   0.896 0.31  0.424 0.603 0.626 0.805 0.401 0.779 0.38  0.933
 0.714 0.464 0.414 0.395 0.829 0.519 0.879 0.808 0.352 0.457 0.664 0.527
 0.513 0.75  0.906 0.362 0.42  0.918 0.517 0.354 0.845 0.738 0.428 0.893
 0.752 0.898 0.599 0.3   0.614 0.621 0.886 0.274 0.387 0.853 0.876 0.386
 0.753 0.871 0.279 0.355 0.256 0.873 0.357 0.952 0.502 0.526 0.224 0.376
 0.202 0.86  0.407 0.846 0.338 0.899 0.472 0.346 0.253 0.323 0.496 0.79
 0.305 0.326 0.306 0.269 0.456 0.77  0.41  0.289 0.8   0.467 0.337 0.874
 0.475 0.258 0.588 0.897 0.89  0.358 0.397 0.967 0.567 0.776 0.313 0.814
 0.403 0.339 0.474 0.264 0.349 0.248 0.984 0.786 0.94  0.149 0.332 0.795
 0.815 0.774 0.691 0.318 0.901 0.311 0.811 0.209 0.793 0.155 0.325 0.512
 0.866 0.369 0.809 0.849 0.367 0.197 0.257 0.559 0.308 0.833 0.285 0.851
 0.331 0.449 0.507 0.201 0.868 0.826 0.87  0.36  0.789 0.2   0.875 0.863
 0.44  0.96  0.321 0.807 0.887 0.361 0.91  0.179 0.249 0.265 0.219 0.865
 0.287 0.206 0.792 0.278 0.229 0.348 0.98  0.935 0.231 0.416 0.455 0.391
 0.329 0.345 0.891 0.914 0.855 0.979 0.864 0.912 0.244 0.    0.15  0.88
 0.34  0.307 0.375 0.882 0.381 0.928 0.262 0.327 0.353 0.465 0.881 0.945
 0.954 0.335 0.378 0.961 0.239 0.913 0.205 0.341 0.413 0.903 0.857 0.432
 0.442 0.84  0.823 0.189 0.328 0.909 0.962 0.281 0.297 0.158 0.267 0.946
 0.282 0.225 0.277 0.965 0.422 0.286 0.298 0.186 0.9  ]

Column: Energy
[7.43e-01 6.65e-01 6.27e-01 7.10e-01 6.80e-01 6.28e-01 6.81e-01 5.33e-01
 3.72e-01 7.54e-01 5.63e-01 3.02e-01 6.60e-01 6.24e-01 9.58e-01 8.52e-01
 4.97e-01 8.12e-01 3.93e-01 5.43e-01 3.27e-01 7.21e-01 8.53e-01 8.59e-01
 6.39e-01 5.51e-01 5.44e-01 6.00e-01 7.84e-01 8.80e-01 5.22e-01 7.32e-01
 7.88e-01 6.58e-01 8.48e-01 3.73e-01 9.08e-01 4.42e-01 8.22e-01 4.35e-01
 7.14e-01 7.20e-01 9.80e-01 7.06e-01 5.91e-01 5.88e-01 3.63e-01 4.44e-01
 7.19e-01 8.43e-01 4.81e-01 4.94e-01 1.27e-01 8.25e-01 7.65e-01 9.27e-01
 9.35e-01 7.61e-01 8.69e-01 6.51e-01 8.40e-01 8.82e-01 5.57e-01 7.77e-01
 8.83e-01 6.66e-01 4.17e-01 4.72e-01 8.05e-01 4.26e-01 9.21e-01 6.36e-01
 8.89e-01 3.14e-01 5.17e-01 6.22e-01 4.39e-01 6.34e-01 7.75e-01 4.13e-01
 8.13e-01 5.93e-01 9.39e-01 6.57e-01 7.80e-01 6.71e-01 4.28e-01 7.18e-01
 9.20e-01 7.72e-01 5.13e-01 4.88e-01 8.09e-01 7.91e-01 8.50e-01 7.68e-01
 6.08e-01 8.16e-01 6.86e-01 6.76e-01 7.83e-01 9.37e-01 2.69e-01 9.22e-01
 4.12e-01 4.85e-01 7.95e-01 8.98e-01 8.20e-01 6.21e-01 4.89e-01 3.62e-01
 7.13e-01 8.31e-01 7.56e-01 8.78e-01 9.46e-01 1.05e-01 8.11e-01 5.39e-01
 4.97e-02 3.79e-01 8.08e-01 8.41e-01 9.24e-01 4.48e-01 7.16e-01 7.48e-01
 7.93e-01 5.14e-01 6.94e-01 8.65e-01 8.02e-01 7.76e-01 9.32e-01 8.67e-01
 6.31e-01 8.81e-01 7.36e-01 7.37e-01 7.39e-01 7.22e-01 6.47e-01 9.54e-01
 7.97e-01 2.59e-01 8.84e-01 5.75e-01 6.88e-01 7.60e-01 5.85e-01 5.70e-01
 9.02e-01 6.75e-01 4.98e-01 4.33e-01 6.19e-01 4.95e-01 8.10e-01 7.50e-01
 3.01e-01 5.59e-01 6.10e-01 7.53e-01 5.87e-01 3.68e-01 8.24e-01 2.13e-01
 9.66e-01 3.99e-01 7.64e-01 7.52e-01 5.99e-01 6.97e-01 7.66e-01 9.59e-01
 7.02e-01 6.32e-01 2.92e-01 9.07e-01 8.55e-01 3.83e-01 6.29e-01 5.27e-01
 5.54e-01 8.96e-01 9.87e-01 7.45e-01 9.36e-01 7.34e-01 5.49e-02 9.34e-01
 7.57e-01 4.75e-01 6.87e-01 4.21e-01 8.72e-01 6.59e-01 5.84e-01 4.41e-01
 4.16e-01 9.19e-01 4.55e-01 4.49e-01 6.49e-01 5.52e-01 5.31e-01 6.48e-01
 4.66e-01 9.61e-01 9.97e-01 2.62e-01 7.78e-01 4.96e-01 9.71e-01 3.28e-01
 7.17e-01 7.08e-01 1.74e-01 9.15e-01 4.60e-01 6.54e-01 9.91e-01 3.74e-01
 7.49e-01 5.00e-01 5.67e-01 9.17e-01 6.33e-01 9.25e-01 4.45e-01 8.85e-01
 3.40e-01 8.47e-01 4.06e-01 8.33e-01 6.61e-01 4.84e-01 8.66e-01 1.77e-01
 4.86e-01 3.03e-01 9.29e-01 6.78e-01 6.69e-01 9.55e-01 5.34e-01 5.72e-01
 6.37e-01 6.17e-01 2.22e-01 8.29e-01 9.44e-01 9.03e-01 7.85e-01 4.99e-01
 7.92e-01 5.18e-01 9.51e-01 6.74e-01 6.07e-01 4.59e-01 2.58e-01 8.57e-01
 4.52e-01 7.55e-01 3.39e-02 8.35e-01 7.74e-01 7.33e-01 8.01e-01 8.76e-01
 6.13e-01 8.46e-01 4.76e-01 5.32e-01 4.27e-01 6.83e-01 6.14e-01 4.57e-01
 6.55e-01 4.70e-01 7.46e-01 6.56e-01 1.97e-01 5.30e-01 8.74e-01 8.91e-01
 7.31e-01 9.23e-01 7.71e-01 9.65e-01 9.45e-01 9.81e-01 7.15e-01 9.16e-01
 6.91e-01 7.00e-01 5.11e-01 6.84e-01 9.11e-01 6.72e-01 7.38e-01 9.42e-01
 4.83e-01 3.60e-01 2.63e-01 6.93e-01 2.88e-01 7.29e-01 6.46e-01 5.77e-01
 8.51e-01 8.60e-01 8.73e-01 8.70e-01 8.44e-01 1.72e-01 5.20e-01 9.63e-01
 3.55e-01 7.40e-01 3.29e-01 7.98e-01 8.14e-01 8.45e-01 1.14e-01 5.68e-01
 6.01e-01 8.15e-01 9.56e-01 7.30e-01 8.77e-01 7.87e-01 6.09e-01 8.18e-01
 5.35e-01 3.89e-01 8.37e-01 2.67e-01 8.63e-01 7.82e-01 3.77e-01 9.33e-01
 6.67e-01 8.39e-01 8.06e-01 4.90e-01 8.36e-01 5.28e-01 7.28e-01 4.67e-01
 6.95e-01 3.69e-01 9.92e-01 8.04e-01 7.03e-01 7.89e-01 5.46e-01 8.26e-01
 9.74e-01 4.02e-01 1.49e-01 3.35e-01 8.68e-01 8.34e-01 7.26e-01 5.79e-01
 9.31e-01 5.26e-01 7.35e-01 7.90e-01 9.13e-01 9.75e-01 8.79e-01 2.80e-01
 3.19e-01 7.42e-01 7.59e-01 8.88e-01 7.62e-01 1.98e-01 4.87e-01 3.70e-01
 6.18e-01 3.58e-01 6.79e-01 7.25e-01 5.71e-01 6.70e-01 5.55e-01 6.64e-01
 7.24e-01 5.78e-01 7.04e-01 5.42e-01 7.27e-01 5.92e-01 8.07e-01 8.00e-01
 8.92e-01 5.41e-01 5.80e-01 6.62e-01 3.10e-01 2.85e-01 3.34e-01 8.54e-01
 7.67e-01 3.20e-01 6.05e-01 7.58e-01 5.64e-01 2.28e-01 8.38e-01 6.52e-01
 6.04e-01 7.96e-01 7.41e-01 6.82e-01 1.85e-01 9.53e-01 5.06e-01 3.46e-01
 3.64e-01 8.97e-01 3.75e-01 7.94e-01 3.36e-01 3.84e-01 4.73e-01 5.16e-01
 9.00e-01 6.03e-01 2.83e-01 4.82e-01 1.13e-01 5.96e-01 4.47e-01 6.35e-01
 6.43e-01 7.05e-01 8.23e-01 5.19e-01 9.73e-01 9.06e-01 7.44e-01 3.25e-01
 5.15e-01 5.47e-01 6.53e-01 6.42e-01 8.86e-01 8.21e-01 8.28e-01 2.16e-01
 4.00e-01 9.82e-01 6.63e-01 9.72e-01 6.98e-01 4.01e-01 6.77e-01 4.77e-01
 4.53e-01 8.49e-01 3.31e-01 8.75e-01 2.95e-01 2.20e-01 8.19e-01 9.40e-01
 5.45e-01 8.58e-01 2.82e-01 6.90e-01 3.80e-01 6.20e-01 7.51e-01 3.78e-01
 7.81e-01 4.51e-01 5.12e-01 4.58e-01 9.77e-01 5.83e-01 4.50e-01 5.25e-01
 6.92e-01 5.03e-01 7.12e-01 4.09e-01 7.23e-01 2.98e-01 9.48e-01 6.45e-01
 7.63e-01 6.44e-01 4.92e-01 9.84e-01 7.86e-01 9.12e-01 3.82e-01 9.57e-01
 5.62e-01 3.88e-01 6.06e-01 4.30e-01 9.85e-01 3.66e-01 5.05e-01 8.17e-01
 4.20e-01 4.14e-01 8.27e-01 4.03e-01 7.69e-01 5.98e-01 4.54e-01 5.56e-01
 5.08e-01 2.27e-01 4.43e-01 3.76e-01 7.09e-01 4.25e-01 6.73e-01 4.32e-01
 3.45e-01 9.14e-01 4.29e-01 6.30e-01 4.22e-01 7.01e-01 4.91e-01 7.47e-01
 1.46e-01 1.53e-01 5.24e-01 5.66e-01 3.32e-01 5.58e-01 9.70e-01 6.99e-01
 9.67e-01 7.70e-01 4.68e-01 6.25e-01 2.03e-01 7.11e-01 9.52e-01 4.69e-01
 3.15e-01 9.68e-01 5.65e-01 6.02e-01 5.48e-01 4.46e-01 8.71e-01 3.49e-01
 5.23e-01 9.83e-01 4.04e-01 6.11e-01 9.50e-01 4.78e-01 2.90e-01 5.38e-01
 5.97e-01 9.10e-01 5.76e-01 5.61e-01 9.41e-01 2.96e-01 1.63e-01 5.89e-01
 8.30e-01 3.44e-01 3.17e-01 4.80e-01 9.60e-01 9.93e-01 9.30e-01 6.68e-01
 8.32e-01 1.81e-01 3.39e-01 5.95e-01 8.90e-01 8.93e-01 9.28e-01 9.01e-01
 9.18e-01 5.86e-01 2.19e-01 4.36e-01 2.74e-01 4.63e-01 8.64e-01 9.76e-01
 3.86e-01 2.65e-01 4.65e-01 9.04e-01 2.12e-01 6.85e-01 9.26e-01 9.49e-01
 8.03e-01 2.31e-01 4.64e-01 5.74e-01 7.99e-01 8.94e-01 6.41e-01 9.22e-02
 3.67e-01 5.36e-01 4.62e-01 6.26e-01 3.07e-01 3.90e-01 4.10e-01 2.94e-01
 3.04e-01 8.99e-01 4.37e-01 3.22e-01 5.49e-01 5.10e-01 4.23e-01 6.16e-01
 3.33e-01 9.05e-01 2.55e-01 9.38e-01 9.64e-01 2.64e-01 5.94e-01 8.56e-01
 8.42e-01 8.87e-01 3.91e-01 5.21e-01 9.62e-01 3.00e-01 9.89e-01 9.69e-01
 2.78e-01 4.56e-01 5.04e-01 9.47e-01 5.37e-01 2.43e-01 4.79e-01 5.82e-01
 2.00e-01 2.91e-01 4.31e-01 6.38e-01 9.43e-01 3.81e-01 5.81e-01 1.38e-01
 3.71e-01 3.38e-01 2.76e-01 5.73e-01 5.29e-02 4.40e-01 2.25e-01 4.19e-01
 7.07e-01 2.39e-01 8.61e-01 2.45e-01 6.96e-01 3.13e-01 2.93e-01 9.40e-02
 2.06e-01 2.37e-01 3.51e-01 3.94e-01 2.10e-01 9.86e-01 3.95e-01 6.89e-01
 7.79e-01 9.79e-01 4.18e-01 5.02e-01 1.83e-01 3.21e-01 2.50e-01 5.90e-01
 9.09e-01 8.62e-01 3.54e-01 2.72e-01 3.30e-01 2.71e-01 2.05e-01 7.36e-02
 2.75e-01 2.38e-01 6.12e-01 3.50e-01 8.95e-01 4.15e-01 3.48e-01 5.40e-01
 2.81e-01 2.42e-01 2.77e-01 3.96e-01 4.34e-01 9.88e-01 1.68e-01 4.74e-01
 6.15e-01 3.47e-01 6.23e-01 3.37e-01 5.09e-01 3.52e-01 6.40e-01 3.05e-01
 5.01e-01 5.60e-01 4.71e-01 5.50e-01 4.61e-01 2.35e-01 3.23e-01 2.73e-01
 2.56e-01 1.73e-01 2.53e-01 4.38e-01 2.03e-05 3.87e-01 6.50e-01 1.65e-01
 4.77e-02 2.33e-01 3.65e-01 4.93e-01 3.43e-01 3.98e-01 1.92e-01 3.08e-01
 4.05e-01 3.53e-01 2.34e-01 1.96e-01 2.07e-01 1.89e-01 2.09e-01 2.11e-01
 1.62e-01 2.24e-01 2.47e-01 5.53e-01 1.78e-01 2.00e-02 3.18e-01 3.59e-01
 4.11e-01 1.55e-01 3.11e-01 3.41e-01 2.60e-01 1.67e-01 2.66e-01 8.80e-02
 2.36e-01 3.07e-02 3.16e-01 1.04e-01 2.41e-01 5.29e-01 1.37e-01 4.07e-01
 5.69e-01 3.24e-01 2.23e-01 2.87e-01 5.07e-01 3.61e-01 2.84e-01 2.70e-01
 1.33e-01 1.95e-01 3.06e-01 3.85e-01 4.08e-01 7.73e-01 2.04e-01 3.57e-01
 2.57e-01 2.28e-02 2.61e-01 1.34e-01 3.97e-01 9.94e-01 7.35e-02 9.78e-01
 3.92e-01 1.40e-01]

Column: Key
[ 2.  7.  0.  9.  6. 11. 10.  4.  5.  3.  1.  8.]

Column: Loudness
[-5.995 -5.171 -9.611 ... -8.78  -5.57  -6.802]

Column: Mode
[1. 0.]

Column: Speechiness
[0.149  0.0305 0.0687 0.0356 0.321  0.0262 0.0871 0.0252 0.0321 0.0494
 0.0312 0.0339 0.0348 0.0565 0.0345 0.119  0.0487 0.0477 0.141  0.0335
 0.0432 0.0792 0.0346 0.0376 0.0907 0.0943 0.0685 0.0777 0.0463 0.0318
 0.03   0.0288 0.103  0.0512 0.0549 0.05   0.0368 0.0353 0.109  0.033
 0.0407 0.0588 0.0303 0.0473 0.199  0.0675 0.0286 0.0295 0.0573 0.0489
 0.0815 0.0271 0.0274 0.0347 0.0933 0.0567 0.0478 0.0364 0.0472 0.0662
 0.124  0.0499 0.0509 0.0454 0.0496 0.322  0.0249 0.025  0.0313 0.153
 0.0644 0.055  0.0374 0.512  0.0469 0.0269 0.0689 0.0428 0.0417 0.0422
 0.0448 0.0304 0.0341 0.0336 0.0316 0.446  0.031  0.0594 0.039  0.271
 0.0256 0.0311 0.0625 0.0423 0.0426 0.0668 0.0334 0.0276 0.0597 0.0528
 0.0366 0.0444 0.0359 0.0704 0.0485 0.0977 0.0577 0.035  0.0278 0.0287
 0.0665 0.0584 0.0383 0.0357 0.0264 0.0392 0.0351 0.065  0.0431 0.0664
 0.0399 0.0652 0.288  0.0284 0.0516 0.0591 0.0917 0.0459 0.0503 0.0793
 0.0458 0.0592 0.113  0.0363 0.0384 0.0495 0.0667 0.082  0.0427 0.0414
 0.0389 0.0382 0.0404 0.0302 0.0301 0.102  0.045  0.161  0.0447 0.0355
 0.0308 0.0435 0.0242 0.458  0.0608 0.211  0.0533 0.303  0.127  0.0547
 0.313  0.0306 0.0521 0.167  0.034  0.0684 0.0506 0.0385 0.0285 0.0319
 0.0243 0.0277 0.0265 0.0325 0.0982 0.0771 0.0789 0.037  0.0993 0.0778
 0.0402 0.067  0.0406 0.0502 0.038  0.164  0.0299 0.0397 0.0589 0.0326
 0.173  0.0504 0.0484 0.296  0.0337 0.0362 0.0292 0.117  0.0785 0.0416
 0.0267 0.0449 0.0897 0.0548 0.0864 0.252  0.0331 0.0293 0.112  0.0605
 0.0581 0.0328 0.0315 0.227  0.0513 0.0693 0.0324 0.0791 0.0386 0.0468
 0.179  0.0255 0.0909 0.0483 0.0436 0.0697 0.0482 0.0615 0.323  0.0296
 0.0531 0.0596 0.0323 0.0408 0.0429 0.0998 0.0343 0.0365 0.0738 0.0798
 0.171  0.0411 0.0554 0.0703 0.0624 0.0803 0.0619 0.0333 0.378  0.0349
 0.0375 0.0394 0.0498 0.036  0.249  0.134  0.168  0.0959 0.0434 0.152
 0.0338 0.0307 0.155  0.028  0.0569 0.032  0.0679 0.0317 0.269  0.0378
 0.0941 0.041  0.0633 0.0534 0.12   0.0398 0.0245 0.28   0.189  0.0553
 0.0415 0.061  0.0659 0.0955 0.0767 0.0322 0.0598 0.029  0.0372 0.0628
 0.0557 0.101  0.0734 0.285  0.057  0.258  0.148  0.0919 0.0413 0.0403
 0.0786 0.0275 0.0332 0.162  0.0279 0.1    0.0395 0.0455 0.224  0.116
 0.0981 0.0405 0.0344 0.0361 0.14   0.106  0.0393 0.126  0.0756 0.409
 0.049  0.0658 0.0297 0.0646 0.0929 0.0694 0.122  0.0282 0.0666 0.0433
 0.058  0.0901 0.0329 0.0886 0.0544 0.0259 0.0437 0.0369 0.0281 0.233
 0.0475 0.0524 0.0641 0.175  0.0856 0.048  0.0676 0.0844 0.0461 0.026
 0.389  0.0465 0.0418 0.35   0.0452 0.0671 0.0283 0.0705 0.0412 0.361
 0.185  0.0443 0.291  0.143  0.357  0.0755 0.071  0.396  0.0852 0.0314
 0.135  0.0945 0.115  0.0788 0.0759 0.046  0.044  0.0719 0.0517 0.37
 0.172  0.0352 0.132  0.0261 0.0425 0.133  0.295  0.0969 0.0884 0.0263
 0.205  0.0507 0.0396 0.0727 0.181  0.0424 0.0809 0.0289 0.0579 0.0546
 0.0438 0.0381 0.062  0.0556 0.0655 0.465  0.118  0.054  0.0441 0.0637
 0.232  0.267  0.0918 0.0298 0.0636 0.0291 0.0421 0.0391 0.0614 0.0922
 0.0535 0.059  0.0582 0.0522 0.0253 0.04   0.0272 0.0294 0.0874 0.177
 0.0508 0.226  0.0462 0.0367 0.0505 0.0409 0.0974 0.17   0.234  0.0525
 0.0701 0.219  0.0574 0.0992 0.0796 0.343  0.042  0.0656 0.0678 0.0623
 0.0699 0.0806 0.0481 0.0564 0.268  0.0445 0.194  0.0471 0.0529 0.0457
 0.0545 0.334  0.0706 0.0657 0.0491 0.053  0.0746 0.0377 0.0996 0.0908
 0.0926 0.0708 0.104  0.195  0.411  0.375  0.0868 0.0707 0.0235 0.027
 0.243  0.0837 0.0944 0.0251 0.128  0.0358 0.0677 0.221  0.0571 0.0379
 0.0587 0.0327 0.139  0.0519 0.0714 0.0794 0.0523 0.0879 0.0536 0.06
 0.0497 0.125  0.0824 0.0342 0.121  0.0913 0.147  0.0829 0.0698 0.0882
 0.0371 0.0479 0.0725 0.0453 0.41   0.0885 0.0686 0.0711 0.274  0.0246
 0.0451 0.0456 0.0309 0.245  0.11   0.0526 0.0538 0.151  0.0741 0.0248
 0.0973 0.075  0.0419 0.0244 0.0493 0.0861 0.043  0.0802 0.0551 0.0832
 0.0542 0.0609 0.0949 0.107  0.373  0.047  0.0575 0.0486 0.0847 0.0568
 0.0537 0.0702 0.0476 0.0273 0.123  0.0947 0.356  0.145  0.08   0.0258
 0.0552 0.056  0.0561 0.051  0.0511 0.0616 0.0639 0.0723 0.0354 0.0845
 0.086  0.27   0.42   0.0878 0.299  0.298  0.0681 0.0464 0.18   0.0629
 0.114  0.0466 0.0903 0.0795 0.146  0.0268 0.142  0.0709 0.0696 0.0751
 0.0875 0.111  0.0638 0.0439 0.0956 0.0488 0.0869 0.0859 0.241  0.0695
 0.136  0.074  0.0527 0.066  0.276  0.183  0.0939 0.0654 0.204  0.0688
 0.0896 0.0559 0.3    0.0842 0.0804 0.072  0.0672 0.0828 0.0952 0.0515
 0.246  0.0645 0.0783 0.0401 0.272  0.217  0.0632 0.0266 0.0763 0.108
 0.0446 0.0758 0.711  0.0595 0.329  0.0593 0.0442 0.0732 0.176  0.0578
 0.138  0.0602 0.251  0.263  0.197  0.0661 0.024  0.0586 0.222  0.0514
 0.0228 0.0948 0.0541 0.0373 0.0576 0.0766 0.0634 0.0916 0.0983 0.0713
 0.0532 0.081  0.236  0.0964 0.207  0.0558 0.0975 0.192  0.0962 0.105
 0.182  0.385  0.266  0.0388 0.0572 0.158  0.0729 0.052  0.156  0.0585
 0.0833 0.0626 0.069  0.264  0.0387 0.0224 0.216  0.077  0.0838 0.0888
 0.0986 0.137  0.231  0.0555 0.0883 0.0932 0.0994 0.188  0.0978 0.0937
 0.0601 0.237  0.346  0.0718 0.0647 0.0805 0.0748 0.0911 0.31   0.21
 0.0613 0.333  0.265  0.0761 0.0923 0.0898 0.0733 0.0841 0.0257 0.129
 0.0851 0.0717 0.064  0.0474 0.0566 0.0611 0.0744 0.206  0.144  0.297
 0.0562 0.262  0.278  0.0772 0.253  0.287  0.0653 0.093  0.223  0.283
 0.0543 0.0853 0.316  0.0721 0.0607 0.533  0.13   0.0631 0.0539 0.247
 0.344  0.087  0.0963 0.302  0.0914 0.0889 0.0237 0.215  0.0784 0.165
 0.0957 0.0715 0.0812 0.0663 0.076  0.0782 0.0501 0.0799 0.209  0.0971
 0.0769 0.0642 0.437  0.347  0.131  0.0835 0.0651 0.25   0.186  0.0747
 0.314  0.068  0.0674 0.301  0.0934 0.318  0.0467 0.0797 0.438  0.0997
 0.0604 0.307  0.0921 0.0976 0.202  0.0728 0.098  0.0726 0.398  0.317
 0.19   0.259  0.184  0.159  0.0894 0.0742 0.244  0.0807 0.0722 0.467
 0.38   0.0961 0.0236 0.0635 0.07   0.0958 0.0739 0.281  0.0622 0.157
 0.0736 0.0649 0.0648 0.0752 0.342  0.0712 0.0735 0.239  0.154  0.0692
 0.0953 0.0518 0.0818 0.4    0.0865 0.214  0.212  0.526  0.0724 0.0979
 0.0787 0.15   0.0872 0.     0.0618 0.0826 0.0753 0.0643 0.0768 0.0745
 0.208  0.0892 0.254  0.0762 0.196  0.0238 0.293  0.327  0.0848 0.235
 0.0831 0.16   0.371  0.275  0.0241 0.394  0.22   0.073  0.0621 0.33
 0.365  0.201  0.085  0.166  0.203  0.0873 0.0492 0.097  0.0774 0.481
 0.363  0.0716 0.0781 0.406  0.0912 0.255  0.26   0.0612 0.0988 0.0583
 0.0987 0.0931 0.0247 0.392  0.326  0.0895 0.218  0.09   0.0779 0.174
 0.0226 0.089  0.191  0.332  0.0814 0.2    0.0606 0.304  0.094  0.079
 0.337  0.311  0.0866 0.0731 0.0938 0.0627 0.091  0.0954 0.36   0.0683

1. Key (kunci musik) sebenarnya adalah kategori, bukan angka, sehingga tidak cocok kalau diperlakukan seperti nilai numerik. Agar tidak menimbulkan perhitungan jarak yang salah, Key diubah menjadi format one-hot.
2. Mode menunjukkan apakah lagu bersifat mayor atau minor, sehingga sudah berupa data biner. Fitur ini tetap dipakai, tetapi distandarkan agar kontribusinya seimbang dengan fitur lainnya saat membandingkan kemiripan lagu.
3. Time Signature (jumlah ketukan per bar) ditemukan memiliki nilai nol yang tidak bermakna. Karena nilai nol tidak relevan secara musik dan fitur ini juga tidak terlalu berpengaruh pada kemiripan audio, maka variabel ini dihapus agar data lebih konsisten dan model lebih andal.

In [ ]:
#Check Missing Values
df.isna().sum()

Track URI               0
Track Name              0
Artist Name(s)          0
Album Name              0
Album Release Date      2
Popularity              0
Artist Genres         255
Danceability          252
Energy                  2
Key                     2
Loudness                2
Mode                    2
Speechiness             2
Acousticness            2
Instrumentalness      102
Liveness                2
Valence                 2
Tempo                   2
Time Signature          2
dtype: int64

Kolom dengan Missing Value
1. Album Release Date -> 2 missing
2. Artist Genres -> 255 missing
3. Danceability -> 252 missing
4. Energy -> 2 missing
5. Key -> 2 missing
6. Loudness -> 2 missing
7. Mode -> 2 missing
8. Speechiness -> 2 missing
9. Acousticness -> 2 missing
10. Instrumentalness -> 102 missing
11. Liveness -> 2 missing
12. Valence -> 2 missing
13. Tempo -> 2 missing

In [ ]:
#Check Outliers
numeric_cols = [
    "Danceability", "Energy", "Loudness", "Speechiness",
    "Acousticness", "Instrumentalness", "Liveness",
    "Valence", "Tempo"
]

outlier_summary = []

for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)][col]

    outlier_summary.append({
        'column': col,
        'outlier_count': outliers.shape[0],
        'outlier_min': outliers.min() if not outliers.empty else None,
        'outlier_max': outliers.max() if not outliers.empty else None
    })

outlier_df = pd.DataFrame(outlier_summary)

print(outlier_df[outlier_df['outlier_count'] > 0])

             column  outlier_count  outlier_min  outlier_max
0      Danceability             34      0.00000        0.228
1            Energy             25      0.00002        0.140
2          Loudness            103    -29.36800      -15.366
3       Speechiness            557      0.11800        0.711
4      Acousticness            231      0.78100        0.987
5  Instrumentalness            999      0.00134        0.973
6          Liveness            239      0.47700        0.982
8             Tempo            116      0.00000      213.654

1. Danceability (34 outlier, 0.000-0.228): Nilai sangat rendah menunjukkan lagu sangat tidak “danceable”. Bisa jadi memang karakter lagunya seperti itu atau data salah, jadi perlu dicek.
2. Energy (25 outlier, 0.00002-0.140): Energy yang sangat rendah biasanya berarti lagu sangat lembut atau minim dinamika. Bisa valid, tapi juga bisa error, jadi perlu dicek.
3. Loudness (103 outlier, -29.368-(-15.039)): Nilai loudness yang sangat rendah menunjukkan suara sangat pelan. Karena cukup banyak outlier, perlu dipertimbangkan untuk ditangani.
4. Speechiness (557 outlier, 0.118-0.711): Nilai tinggi berarti banyak suara bicara (misalnya podcast atau rap). Karena jumlah outlier sangat banyak, ini bisa memengaruhi hasil clustering.
5. Acousticness (231 outlier, 0.781-0.987): Menunjukkan lagu sangat akustik. Bisa valid, tapi karena banyak outlier, perlu dicek.
6. Instrumentalness (999 outlier, 0.00134-0.973): Outlier sangat banyak, menunjukkan banyak lagu instrumental atau data tidak konsisten. Perlu di-handle agar tidak memengaruhi model.
7. Liveness (239 outlier, 0.474-0.982): Nilai tinggi menunjukkan rekaman live (konser). Bisa valid, tapi tetap perlu dicek karena cukup banyak outlier.
8. Tempo (116 outlier, 0.000–213.654): Tempo 0 jelas tidak realistis, dan tempo sangat tinggi juga jarang. Jadi perlu ditangani.

## Handle Data Problems

In [ ]:
#Hanlde Irrelevant Value
df["Time Signature"] = df["Time Signature"].replace(0, np.nan)
df["Time Signature"].fillna(df["Time Signature"].median(), inplace=True)

Nilai 0 pada Time Signature tidak valid secara musik, jadi diganti menjadi missing agar tidak mempengaruhi analisis, lalu diisi dengan median untuk menjaga kelengkapan data.

In [ ]:
#Handle Missing Value
df = df.dropna()

Missng value didrop karena mengisi missing pada fitur audio penting bisa membuat data tidak realistis, sementara dataset masih cukup besar sehingga kehilangan beberapa baris tidak masalah.

In [ ]:
#Handle Outliers Use IQR Capping
outlier_cols = [
    "Danceability", "Energy", "Loudness", "Speechiness",
    "Acousticness", "Instrumentalness", "Liveness", "Tempo"
]

for col in outlier_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    # cap values
    df[col] = np.where(df[col] < lower, lower, df[col])
    df[col] = np.where(df[col] > upper, upper, df[col])

Outlier pada fitur audio bisa valid karena beberapa lagu memang memiliki karakter ekstrem (misalnya instrumental atau live), namun nilai ekstrem ini dapat mengacaukan perhitungan kemiripan antar lagu dalam sistem rekomendasi berbasis konten karena distribusi fitur audio biasanya tidak normal, IQR capping lebih aman daripada z-score, dan metode ini menjaga data tetap utuh dengan hanya membatasi nilai ekstrem tanpa menghapus data.

In [ ]:
#One Hot Encoding
from sklearn.preprocessing import OneHotEncoder

df["Key"] = df["Key"].astype("Int64")
df["Time Signature"] = df["Time Signature"].astype("Int64")

ohe = OneHotEncoder(handle_unknown="ignore",sparse_output=False)

encoded = ohe.fit_transform(df[["Key", "Time Signature"]])
encoded_cols = ohe.get_feature_names_out(["Key", "Time Signature"])
encoded_df = pd.DataFrame(encoded, columns=encoded_cols, index=df.index)

df = pd.concat([df.drop(columns=["Key", "Time Signature"]), encoded_df], axis=1)

Variabel Key dan Time Signature pada dasarnya adalah kategori, bukan angka yang punya urutan atau jarak. Kalau dibiarkan sebagai angka, model bisa menganggap misalnya Key 1 lebih “dekat” dengan Key 2 dibanding Key 11, padahal secara musik tidak seperti itu. One Hot Encoding mengubah setiap kategori menjadi kolom terpisah sehingga model tidak menganggap ada urutan atau jarak antar kategori, sehingga perhitungan kemiripan atau model prediksi jadi lebih akurat.

In [ ]:
#Scaling
from sklearn.preprocessing import StandardScaler

num_cols = ["Danceability", "Energy", "Loudness", "Speechiness",
            "Acousticness", "Instrumentalness", "Liveness",
            "Valence", "Tempo"]

scaler = StandardScaler()
audio_scaled = scaler.fit_transform(df[num_cols])

Scaling dilakukan agar semua fitur audio memiliki skala yang sama, sehingga fitur dengan rentang nilai besar tidak mendominasi saat menghitung kemiripan atau saat dipakai dalam model. StandardScaler dipilih karena mengubah data menjadi distribusi dengan mean 0 dan standar deviasi 1, sehingga cocok untuk fitur yang memiliki skala dan distribusi berbeda seperti danceability, loudness, dan tempo.

# b. Create a content-based recommendation system, implemented as a function that takes a text input and returns five suggested items!

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

#Text Feature
df["text_feature"] = df["Track Name"] + " " + df["Artist Name(s)"] + " " + df["Artist Genres"]

#TF-IDF
tfidf = TfidfVectorizer(stop_words="english")
tfidf_matrix = tfidf.fit_transform(df["text_feature"])

In [ ]:
#Keyword Detection + threshold
def detect_keywords(text):
    text = text.lower()
    return {
        "fast": any(k in text for k in ["fast", "tempo", "upbeat", "quick"]),
        "slow": any(k in text for k in ["slow", "calm", "relax", "chill"]),
        "dance": any(k in text for k in ["dance", "edm", "club"]),
        "energetic": any(k in text for k in ["energetic", "powerful"]),
        "acoustic": "acoustic" in text,
        "instrumental": any(k in text for k in ["instrumental", "piano", "guitar"]),
        "rap": any(k in text for k in ["rap", "spoken", "hip hop"]),
        "happy": any(k in text for k in ["happy", "joy", "fun"]),
        "sad": any(k in text for k in ["sad", "melancholy", "emotional"]),
        "live": "live" in text
    }

def apply_threshold(df, keywords):
    mask = pd.Series(True, index=df.index)

    if keywords["fast"]:
        mask &= df["Tempo"] > 120
    if keywords["slow"]:
        mask &= df["Tempo"] < 90
    if keywords["dance"]:
        mask &= df["Energy"] > 0.6
    if keywords["energetic"]:
        mask &= df["Energy"] > 0.75
    if keywords["acoustic"]:
        mask &= df["Acousticness"] > 0.6
    if keywords["instrumental"]:
        mask &= df["Instrumentalness"] > 0.6
    if keywords["rap"]:
        mask &= df["Speechiness"] > 0.4
    if keywords["happy"]:
        mask &= df["Valence"] > 0.6
    if keywords["sad"]:
        mask &= df["Valence"] < 0.4
    if keywords["live"]:
        mask &= df["Liveness"] > 0.5

    return mask

In [ ]:
def recommend(text_input, top_n=5):
    keywords = detect_keywords(text_input)

    mask = apply_threshold(df, keywords)
    filtered_df = df[mask].copy()

    if len(filtered_df) < top_n:
        filtered_df = df.copy()

    tfidf_filtered = TfidfVectorizer(stop_words="english")
    tfidf_matrix_filtered = tfidf_filtered.fit_transform(filtered_df["text_feature"])

    audio_scaled_filtered = scaler.transform(filtered_df[num_cols])

    input_vec = tfidf_filtered.transform([text_input])
    text_sim = cosine_similarity(input_vec, tfidf_matrix_filtered).flatten()

    audio_sim = cosine_similarity(audio_scaled_filtered, audio_scaled_filtered)

    combined_scores = 0.5 * text_sim + 0.5 * np.mean(audio_sim, axis=1)

    top_indices = combined_scores.argsort()[-top_n:][::-1]

    return filtered_df.iloc[top_indices][["Track Name", "Artist Name(s)", "Artist Genres"]]

# c. Provide a minimum of three inputs to the function and examine if the recommendations correspond to each input!

In [ ]:
inputs = [
    "energetic dance pop",
    "calm acoustic guitar",
    "upbeat EDM track",
    "fast tempo dance track",
    "piano instrumental"
]

from IPython.display import display, Markdown

for i, inp in enumerate(inputs, 1):
    display(Markdown(f"### 🎧 Input {i}: *{inp}*"))

    rec = recommend(inp, top_n=5).reset_index(drop=True)
    rec.index += 1
    rec = rec.rename(columns={
        "Track Name": "Track",
        "Artist Name(s)": "Artist",
        "Artist Genres": "Genres"
    })

    display(rec)

### 🎧 Input 1: *energetic dance pop*

,Track,Artist,Genres
1,Lonely,Joel Corry,"dance pop,pop dance,uk dance"
2,Came Here for Love,"Sigala, Ella Eyre","dance pop,edm,pop dance,uk dance,uk pop,dance ..."
3,Never Gonna Not Dance Again,P!nk,"dance pop,pop"
4,I'm All Yours,"Jay Sean, Pitbull","dance pop,pop,pop rap,dance pop,miami hip hop,pop"
5,Love on Me,"Galantis, Hook N Sling","dance pop,edm,pop,pop dance,australian dance,p..."

### 🎧 Input 2: *calm acoustic guitar*

,Track,Artist,Genres
1,Calm Down,Killing Heidi,"australian alternative rock,australian rock"
2,Guitar Band,Stevie Wright,australian rock
3,Spanish Guitar,Toni Braxton,"contemporary r&b,dance pop,r&b,urban contemporary"
4,Collide - Acoustic Version,Howie Day,"acoustic pop,neo mellow,pop rock"
5,What Do You Mean? - Acoustic,Justin Bieber,"canadian pop,pop"

### 🎧 Input 3: *upbeat EDM track*

,Track,Artist,Genres
1,One Track Mind,Bobby Lewis,"doo-wop,rhythm and blues"
2,Light Years Away,"Tiësto, DBX","big room,brostep,dutch edm,edm,house,pop dance..."
3,The Nights,Avicii,"edm,pop,pop dance"
4,Come & Go (with Marshmello),"Juice WRLD, Marshmello","chicago rap,melodic rap,rap,brostep,edm,pop,pr..."
5,Red Lights,Tiësto,"big room,brostep,dutch edm,edm,house,pop dance..."

### 🎧 Input 4: *fast tempo dance track*

,Track,Artist,Genres
1,One Track Mind,Bobby Lewis,"doo-wop,rhythm and blues"
2,We Own It (Fast & Furious),"2 Chainz, Wiz Khalifa","atl hip hop,hip hop,pop rap,rap,southern hip h..."
3,With Ur Love (feat. Mike Posner),"Cher Lloyd, Mike Posner","dance pop,pop,post-teen pop,talent show,dance ..."
4,Magic Number,"The Potbelleez, B.o.B","aussietronica,australian dance,australian hous..."
5,If I Go,Ella Eyre,"dance pop,talent show,uk dance,uk pop"

### 🎧 Input 5: *piano instrumental*

,Track,Artist,Genres
1,Green Onions,Booker T. & the M.G.'s,"blues,classic soul,instrumental funk,instrumen..."
2,Soul Limbo,Booker T. & the M.G.'s,"blues,classic soul,instrumental funk,instrumen..."
3,Dance Wiv Me,Dizzee Rascal,"grime,instrumental grime"
4,Something I Need,OneRepublic,"piano rock,pop"
5,Love Runs Out,OneRepublic,"piano rock,pop"

## Kesimpulan

Sistem rekomendasi musik yang dibangun menggunakan pendekatan content-based recommendation dengan memanfaatkan kesamaan teks (text similarity) dan karakteristik audio dari setiap lagu. Deskripsi input pengguna diubah menjadi representasi vektor menggunakan TF-IDF, kemudian dihitung tingkat kemiripannya dengan data lagu menggunakan cosine similarity.

Untuk meningkatkan relevansi hasil rekomendasi, sistem juga menerapkan proses filtering berdasarkan kata kunci pada input pengguna, seperti dance, acoustic, EDM, fast tempo, dan instrumental. Kata kunci tersebut digunakan untuk menyaring lagu berdasarkan fitur audio (misalnya energy, tempo, acousticness, dan instrumentalness) serta genre, sehingga lagu yang tidak sesuai konteks dapat dieliminasi.

Hasil evaluasi menunjukkan bahwa setelah dilakukan perbaikan pada mekanisme filtering dan penghapusan fallback yang terlalu permisif, rekomendasi yang dihasilkan menjadi lebih konsisten dengan deskripsi input pengguna. Dengan demikian, sistem ini mampu memberikan rekomendasi musik yang lebih relevan dan mencerminkan preferensi pengguna secara lebih akurat.